version: "3"
services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - assets:/var/jenkins_home
    networks: 
      - "main_bridge"

  web:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - assets:/usr/local/apache2/htdocs/
    networks: 
      - "main_bridge" 

networks:
  main_bridge: {}

volumes:
  assets: {}