FROM nginx:latest

USER root

RUN apt-get update && apt-get install tree

WORKDIR /usr/share/nginx/html/

RUN rm -rf /usr/share/nginx/html/*

COPY ./artifacts /usr/share/nginx/html/

RUN tree -H '.' -L 1 --noreport --charset utf-8 -o index.html